### ISSUE TITLE
FDA Approval Documents

### ISSUE THREAD

**Issue by chackoge** [gladstone-institutes/bibliometrics#1]
HI Alex- which documents did you use to find foundational references from the FDA approval process for ipilimumab? The Medical Review I found had only one reference in it. Thanks very much.

**Comment by AlexanderPico** [comment]
We only started with 2 references:

https://github.com/gladstone-institutes/bibliometrics/blob/master/input/Ipilimumab-FDA-NDA-Medical-Clinpharm.txt

One from the Medial Review and one from the Clinical Pharmacology document.

**Comment by chackoge** [comment]
In fact, you may have mentioned this earlier. I'm doing a scrape myself and I hope we can find some more documents to add to this list. We will share of course. It's too bad that an FDA Approval Summary paper on ipilimumab wasn't published - maybe one is forthcoming? This thread may also underscore a point you've made once before, to invest SME effort in assembling the seed set of pmids that is used to find cited references.
